---
name: coverage
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install DuckDB
        run: |
          mkdir duckdb && \
          cd duckdb && \
          curl -L https://github.com/duckdb/duckdb/releases/download/v1.3.2/libduckdb-linux-amd64.zip > libduckdb.zip && \
          unzip libduckdb.zip
        working-directory: /opt/
      - name: Install tarpaulin.
        run: cargo install cargo-tarpaulin
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --out xml --engine llvm --features log,serde,syn,tz
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          DUCKDB_INCLUDE_DIR: /opt/duckdb
          DUCKDB_LIB_DIR: /opt/duckdb
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lukesneeringer/datetime-rs
          fail_ci_if_error: true
